// AUTO-GENERATED by scripts/refresh-prices.ts on 2026-05-17.
// Do not edit by hand — re-run the script to refresh.
// The hand-authored seed lives in offers.seed.ts.
// Prices marked source: 'scrape' are live retailer prices fetched via
// TinyFish; source: 'manual' means the fetch missed and the value is the
// verified manufacturer RRP fallback.

import type { Offer } from './types';

export const OFFERS: Offer[] = [
  {
    "productId": "lego-21261-wolf-stronghold",
    "storeId": "amazon",
    "price": 34.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CV2KC5RL",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.11,
      "unit": "piece"
    },
    "capturedAt": "2026-05-17",
    "source": "manual"
  },
  {
    "productId": "lego-21261-wolf-stronghold",
    "storeId": "lego",
    "price": 34.99,
    "currency": "USD",
    "url": "https://www.lego.com/en-us/product/the-wolf-stronghold-21261",
    "inStock": true,
    "shippingDays": {
      "min": 3,
      "max": 5
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.11,
      "unit": "piece"
    },
    "capturedAt": "2026-05-17",
    "source": "scrape"
  },
  {
    "productId": "lego-21260-cherry-blossom-garden",
    "storeId": "amazon",
    "price": 27.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CV297ML5",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.09,
      "unit": "piece"
    },
    "capturedAt": "2026-05-17",
    "source": "manual"
  },
  {
    "productId": "lego-21260-cherry-blossom-garden",
    "storeId": "lego",
    "price": 27.99,
    "currency": "USD",
    "url": "https://www.lego.com/en-us/product/the-cherry-blossom-garden-21260",
    "inStock": true,
    "shippingDays": {
      "min": 3,
      "max": 5
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.09,
      "unit": "piece"
    },
    "capturedAt": "2026-05-17",
    "source": "scrape"
  },
  {
    "productId": "lego-75387-boarding-tantive-iv",
    "storeId": "amazon",
    "price": 54.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CGY4QJTC",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.11,
      "unit": "piece"
    },
    "capturedAt": "2026-05-17",
    "source": "manual"
  },
  {
    "productId": "lego-75387-boarding-tantive-iv",
    "storeId": "lego",
    "price": 54.99,
    "currency": "USD",
    "url": "https://www.lego.com/en-us/product/boarding-the-tantive-iv-75387",
    "inStock": true,
    "shippingDays": {
      "min": 3,
      "max": 5
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.11,
      "unit": "piece"
    },
    "capturedAt": "2026-05-17",
    "source": "scrape"
  },
  {
    "productId": "minecraft-creeper-plush-8in",
    "storeId": "amazon",
    "price": 10.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B08HR84LWQ",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "capturedAt": "2026-05-17",
    "source": "scrape"
  },
  {
    "productId": "minecraft-creeper-plush-16in",
    "storeId": "amazon",
    "price": 24.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CNJGRZVH",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "capturedAt": "2026-05-17",
    "source": "manual"
  },
  {
    "productId": "minecraft-cuutopia-creeper-plush",
    "storeId": "amazon",
    "price": 19.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B09QLGYM6T",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "capturedAt": "2026-05-17",
    "source": "manual"
  },
  {
    "productId": "minecraft-game-switch",
    "storeId": "amazon",
    "price": 29.83,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B07D13QGXM",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "capturedAt": "2026-05-17",
    "source": "scrape"
  },
  {
    "productId": "beyblade-x-xtreme-battle-set",
    "storeId": "amazon",
    "price": 39.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CQ3HMP9M",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "capturedAt": "2026-05-17",
    "source": "manual"
  },
  {
    "productId": "beyblade-x-drop-attack-battle-set",
    "storeId": "amazon",
    "price": 29.59,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0DN6YTNYZ",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "capturedAt": "2026-05-17",
    "source": "scrape"
  },
  {
    "productId": "beyblade-x-sword-dran-starter",
    "storeId": "amazon",
    "price": 9.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CS8L1HGM",
    "inStock": true,
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "capturedAt": "2026-05-17",
    "source": "manual"
  }
];

export const getOffersFor = (productId: string): Offer[] =>
  OFFERS.filter((o) => o.productId === productId);
