// AUTO-GENERATED by scripts/crawl_prices.py on 2026-05-17.
// Do not edit by hand — re-run the script to refresh.
// The hand-authored seed lives in offers.seed.ts.
// Prices marked source: 'scrape' are live retailer prices fetched
// via Crawl4AI; source: 'manual' means the crawl missed and the
// value is the verified manufacturer RRP fallback.

import type { Offer } from './types';

export const OFFERS: Offer[] = [
  {
    "productId": "lego-21261-wolf-stronghold",
    "storeId": "amazon",
    "price": 26.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CV2KC5RL",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.11,
      "unit": "piece"
    }
  },
  {
    "productId": "lego-21261-wolf-stronghold",
    "storeId": "lego",
    "price": 34.99,
    "currency": "USD",
    "url": "https://www.lego.com/en-us/product/the-wolf-stronghold-21261",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 3,
      "max": 5
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.11,
      "unit": "piece"
    }
  },
  {
    "productId": "lego-21260-cherry-blossom-garden",
    "storeId": "amazon",
    "price": 19.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CV297ML5",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.09,
      "unit": "piece"
    }
  },
  {
    "productId": "lego-21260-cherry-blossom-garden",
    "storeId": "lego",
    "price": 27.99,
    "currency": "USD",
    "url": "https://www.lego.com/en-us/product/the-cherry-blossom-garden-21260",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 3,
      "max": 5
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.09,
      "unit": "piece"
    }
  },
  {
    "productId": "lego-75387-boarding-tantive-iv",
    "storeId": "amazon",
    "price": 54.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CGY4QJTC",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.11,
      "unit": "piece"
    }
  },
  {
    "productId": "lego-75387-boarding-tantive-iv",
    "storeId": "lego",
    "price": 54.99,
    "currency": "USD",
    "url": "https://www.lego.com/en-us/product/boarding-the-tantive-iv-75387",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 3,
      "max": 5
    },
    "freeShippingThreshold": 35,
    "unitPrice": {
      "value": 0.11,
      "unit": "piece"
    }
  },
  {
    "productId": "minecraft-creeper-plush-8in",
    "storeId": "amazon",
    "price": 10.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B08HR84LWQ",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "minecraft-creeper-plush-8in",
    "storeId": "walmart",
    "price": 14.99,
    "currency": "USD",
    "url": "https://www.walmart.com/ip/Minecraft-Basic-Plush-Creeper-Stuffed-Animal-8-inch-Soft-Doll-Inspired-by-Video-Game-Character/277349703",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "manual",
    "shippingDays": {
      "min": 2,
      "max": 4
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "minecraft-creeper-plush-16in",
    "storeId": "amazon",
    "price": 19.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CNJGRZVH",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "minecraft-creeper-plush-16in",
    "storeId": "walmart",
    "price": 24.99,
    "currency": "USD",
    "url": "https://www.walmart.com/ip/Minecraft-Creeper-16-in-Scale-Jumbo-Plush-Figure-with-Pixelated-Design-Game/12909910834",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "manual",
    "shippingDays": {
      "min": 2,
      "max": 4
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "minecraft-cuutopia-creeper-plush",
    "storeId": "amazon",
    "price": 19.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B09QLGYM6T",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "minecraft-cuutopia-creeper-plush",
    "storeId": "target",
    "price": 19.99,
    "currency": "USD",
    "url": "https://www.target.com/p/mattel-minecraft-cuutopia-creeper-plush-10-inch-soft-rounded-pillow-doll/-/A-1001588773",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "manual",
    "shippingDays": {
      "min": 2,
      "max": 4
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "minecraft-game-switch",
    "storeId": "amazon",
    "price": 29.83,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B07D13QGXM",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "minecraft-game-switch",
    "storeId": "target",
    "price": 29.99,
    "currency": "USD",
    "url": "https://www.target.com/p/minecraft-nintendo-switch/-/A-53662394",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "manual",
    "shippingDays": {
      "min": 2,
      "max": 4
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "beyblade-x-xtreme-battle-set",
    "storeId": "amazon",
    "price": 33.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CQ3HMP9M",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "beyblade-x-xtreme-battle-set",
    "storeId": "walmart",
    "price": 39.99,
    "currency": "USD",
    "url": "https://www.walmart.com/ip/Beyblade-X-Xtreme-Battle-Set-with-Beystadium-2-Right-Spinning-Battling-Tops-and-2-Launchers/5455100107",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "manual",
    "shippingDays": {
      "min": 2,
      "max": 4
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "beyblade-x-drop-attack-battle-set",
    "storeId": "amazon",
    "price": 29.59,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0DN6YTNYZ",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "beyblade-x-drop-attack-battle-set",
    "storeId": "target",
    "price": 39.99,
    "currency": "USD",
    "url": "https://www.target.com/p/beyblade-x-drop-attack-battle-set/-/A-93565570",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "manual",
    "shippingDays": {
      "min": 2,
      "max": 4
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "beyblade-x-sword-dran-starter",
    "storeId": "amazon",
    "price": 9.99,
    "currency": "USD",
    "url": "https://www.amazon.com/dp/B0CS8L1HGM",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "scrape",
    "shippingDays": {
      "min": 1,
      "max": 2
    },
    "freeShippingThreshold": 35
  },
  {
    "productId": "beyblade-x-sword-dran-starter",
    "storeId": "gamestop",
    "price": 9.99,
    "currency": "USD",
    "url": "https://www.gamestop.com/toys-games/fidget-toys/products/hasbro-beyblade-x-dran-3-60f-starter-pack/20010503.html",
    "inStock": true,
    "capturedAt": "2026-05-17",
    "source": "manual",
    "shippingDays": {
      "min": 3,
      "max": 6
    },
    "freeShippingThreshold": 59
  }
];

export const getOffersFor = (productId: string): Offer[] =>
  OFFERS.filter((o) => o.productId === productId);
