import type { Offer } from './types';

// V1 seed offers.
//
// Each offer's BASE price is the real manufacturer RRP (sourced from official
// LEGO / Mattel / Hasbro / Nintendo listings, May 2026). Per-retailer variation
// is MODELED, not individually verified: a live per-store price requires the
// phase-2 scraping/API backend described in PRD-04. Modeling assumptions:
//   - LEGO Shop / GameStop / Best Buy: at RRP
//   - Amazon: at or slightly below RRP
//   - Walmart / Target: often a few percent below RRP
// capturedAt is the seed date; PRD-04's 14-day staleness rule surfaces this
// honestly in the UI ("Check before buying").
//
// 2026-released LEGO sets that are not yet shelf-available in May 2026 are
// included where the official price is published; inStock reflects buyability.

const CAPTURED = '2026-05-15';

const FREE_SHIP = {
  amazon: 35,
  target: 35,
  walmart: 35,
  lego: 35,
  bestbuy: 35,
  gamestop: 59,
} as const;

export const SEED_OFFERS: Offer[] = [
  // --- LEGO Minecraft: The Warden Encounter 21274 (RRP $34.99) ---
  {
    productId: 'lego-21274-warden-encounter',
    storeId: 'amazon',
    price: 31.99,
    currency: 'USD',
    url: 'https://www.amazon.com/dp/B0DRW63X1Z',
    inStock: true,
    shippingDays: { min: 1, max: 2 },
    freeShippingThreshold: FREE_SHIP.amazon,
    unitPrice: { value: 0.13, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21274-warden-encounter',
    storeId: 'lego',
    price: 34.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/the-warden-encounter-21274',
    inStock: true,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.15, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21274-warden-encounter',
    storeId: 'target',
    price: 33.49,
    currency: 'USD',
    url: 'https://www.target.com/s?searchTerm=lego+minecraft+21274',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.target,
    unitPrice: { value: 0.14, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- LEGO Minecraft: The Crafting Table 21265 (RRP $259.99) ---
  {
    productId: 'lego-21265-crafting-table',
    storeId: 'lego',
    price: 259.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/the-crafting-table-21265',
    inStock: true,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.22, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21265-crafting-table',
    storeId: 'amazon',
    price: 249.95,
    currency: 'USD',
    url: 'https://www.amazon.com/dp/B0CRX64YFN',
    inStock: true,
    shippingDays: { min: 1, max: 2 },
    freeShippingThreshold: FREE_SHIP.amazon,
    unitPrice: { value: 0.21, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21265-crafting-table',
    storeId: 'bestbuy',
    price: 259.99,
    currency: 'USD',
    url: 'https://www.bestbuy.com/product/lego-minecraft-the-crafting-table-21265/JXPLL2Q4W5',
    inStock: true,
    shippingDays: { min: 2, max: 5 },
    freeShippingThreshold: FREE_SHIP.bestbuy,
    unitPrice: { value: 0.22, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- LEGO Minecraft: Chicken Rider Desert Attack 21592 (RRP $9.99) ---
  {
    productId: 'lego-21592-chicken-rider',
    storeId: 'lego',
    price: 9.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/chicken-rider-desert-attack-21592',
    inStock: true,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.13, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21592-chicken-rider',
    storeId: 'walmart',
    price: 9.97,
    currency: 'USD',
    url: 'https://www.walmart.com/search?q=lego+minecraft+21592',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.walmart,
    unitPrice: { value: 0.13, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21592-chicken-rider',
    storeId: 'target',
    price: 9.99,
    currency: 'USD',
    url: 'https://www.target.com/s?searchTerm=lego+minecraft+21592',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.target,
    unitPrice: { value: 0.13, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- LEGO Minecraft: Surviving The First Night 21593 (RRP $14.99) ---
  {
    productId: 'lego-21593-surviving-first-night',
    storeId: 'lego',
    price: 14.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/surviving-the-first-night-21593',
    inStock: true,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.08, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21593-surviving-first-night',
    storeId: 'amazon',
    price: 13.99,
    currency: 'USD',
    url: 'https://www.amazon.com/s?k=lego+minecraft+21593',
    inStock: true,
    shippingDays: { min: 1, max: 2 },
    freeShippingThreshold: FREE_SHIP.amazon,
    unitPrice: { value: 0.07, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- LEGO Minecraft: The Ender Dragon 21595 (RRP $59.99) ---
  {
    productId: 'lego-21595-ender-dragon',
    storeId: 'lego',
    price: 59.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/the-ender-dragon-21595',
    inStock: true,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.08, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21595-ender-dragon',
    storeId: 'amazon',
    price: 56.99,
    currency: 'USD',
    url: 'https://www.amazon.com/s?k=lego+minecraft+21595',
    inStock: true,
    shippingDays: { min: 1, max: 2 },
    freeShippingThreshold: FREE_SHIP.amazon,
    unitPrice: { value: 0.07, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21595-ender-dragon',
    storeId: 'target',
    price: 59.99,
    currency: 'USD',
    url: 'https://www.target.com/s?searchTerm=lego+minecraft+21595',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.target,
    unitPrice: { value: 0.08, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- LEGO Minecraft: Ghast Station 21597 (RRP $29.99) ---
  {
    productId: 'lego-21597-ghast-station',
    storeId: 'lego',
    price: 29.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/ghast-station-21597',
    inStock: true,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.11, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-21597-ghast-station',
    storeId: 'walmart',
    price: 28.88,
    currency: 'USD',
    url: 'https://www.walmart.com/search?q=lego+minecraft+21597',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.walmart,
    unitPrice: { value: 0.1, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- Minecraft Creeper Plush 8" (RRP $24.95) ---
  {
    productId: 'minecraft-creeper-plush-8in',
    storeId: 'amazon',
    price: 22.99,
    currency: 'USD',
    url: 'https://www.amazon.com/dp/B08HR84LWQ',
    inStock: true,
    shippingDays: { min: 1, max: 2 },
    freeShippingThreshold: FREE_SHIP.amazon,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'minecraft-creeper-plush-8in',
    storeId: 'target',
    price: 19.99,
    currency: 'USD',
    url: 'https://www.target.com/p/-/A-81510710',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.target,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'minecraft-creeper-plush-8in',
    storeId: 'walmart',
    price: 21.47,
    currency: 'USD',
    url: 'https://www.walmart.com/search?q=minecraft+creeper+plush',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.walmart,
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- Minecraft Enderman Plush 7" (RRP $19.99) ---
  {
    productId: 'minecraft-enderman-plush-7in',
    storeId: 'amazon',
    price: 18.49,
    currency: 'USD',
    url: 'https://www.amazon.com/dp/B00F65I83A',
    inStock: true,
    shippingDays: { min: 1, max: 3 },
    freeShippingThreshold: FREE_SHIP.amazon,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'minecraft-enderman-plush-7in',
    storeId: 'walmart',
    price: 17.99,
    currency: 'USD',
    url: 'https://www.walmart.com/search?q=minecraft+enderman+plush',
    inStock: true,
    shippingDays: { min: 2, max: 5 },
    freeShippingThreshold: FREE_SHIP.walmart,
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- Minecraft — Nintendo Switch (RRP $29.99) ---
  {
    productId: 'minecraft-game-switch',
    storeId: 'amazon',
    price: 24.99,
    currency: 'USD',
    url: 'https://www.amazon.com/dp/B07D13QGXM',
    inStock: true,
    shippingDays: { min: 1, max: 2 },
    freeShippingThreshold: FREE_SHIP.amazon,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'minecraft-game-switch',
    storeId: 'gamestop',
    price: 29.99,
    currency: 'USD',
    url: 'https://www.gamestop.com/video-games/nintendo-switch/products/minecraft---nintendo-switch/171236.html',
    inStock: true,
    shippingDays: { min: 3, max: 6 },
    freeShippingThreshold: FREE_SHIP.gamestop,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'minecraft-game-switch',
    storeId: 'target',
    price: 27.99,
    currency: 'USD',
    url: 'https://www.target.com/s?searchTerm=minecraft+nintendo+switch',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.target,
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- Minecraft — Xbox Bedrock Edition (RRP $19.99) ---
  {
    productId: 'minecraft-game-xbox',
    storeId: 'gamestop',
    price: 19.99,
    currency: 'USD',
    url: 'https://www.gamestop.com/search/?q=minecraft+xbox',
    inStock: true,
    shippingDays: { min: 3, max: 6 },
    freeShippingThreshold: FREE_SHIP.gamestop,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'minecraft-game-xbox',
    storeId: 'bestbuy',
    price: 19.99,
    currency: 'USD',
    url: 'https://www.bestbuy.com/site/searchpage.jsp?st=minecraft+xbox',
    inStock: true,
    shippingDays: { min: 2, max: 5 },
    freeShippingThreshold: FREE_SHIP.bestbuy,
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- LEGO Star Wars Din Djarin & Grogu Speeder Bike 75408 (RRP $9.99) ---
  {
    productId: 'lego-75408-mandalorian-grogu-speeder',
    storeId: 'lego',
    price: 9.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/din-djarin-and-grogu-s-speeder-bike-75408',
    inStock: true,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.17, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-75408-mandalorian-grogu-speeder',
    storeId: 'target',
    price: 9.99,
    currency: 'USD',
    url: 'https://www.target.com/s?searchTerm=lego+star+wars+75408',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.target,
    unitPrice: { value: 0.17, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- LEGO Star Wars Cobb Vanth & Cad Bane Speeder 75409 (RRP $34.99) ---
  {
    productId: 'lego-75409-cobb-vanth-cad-bane',
    storeId: 'lego',
    price: 34.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/75409',
    inStock: true,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.17, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-75409-cobb-vanth-cad-bane',
    storeId: 'amazon',
    price: 32.99,
    currency: 'USD',
    url: 'https://www.amazon.com/s?k=lego+star+wars+75409',
    inStock: true,
    shippingDays: { min: 1, max: 2 },
    freeShippingThreshold: FREE_SHIP.amazon,
    unitPrice: { value: 0.16, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- LEGO City Coast Guard Rescue Boat 60440 (RRP $14.99) ---
  {
    productId: 'lego-60440-city-coast-guard',
    storeId: 'lego',
    price: 14.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/60440',
    inStock: true,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.09, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-60440-city-coast-guard',
    storeId: 'walmart',
    price: 13.97,
    currency: 'USD',
    url: 'https://www.walmart.com/search?q=lego+city+60440',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.walmart,
    unitPrice: { value: 0.08, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- LEGO Technic Fast & Furious Dodge Charger R/T 42231 (RRP $159.99) ---
  {
    productId: 'lego-42231-fast-furious-charger',
    storeId: 'lego',
    price: 159.99,
    currency: 'USD',
    url: 'https://www.lego.com/en-us/product/42231',
    inStock: false,
    shippingDays: { min: 3, max: 5 },
    freeShippingThreshold: FREE_SHIP.lego,
    unitPrice: { value: 0.11, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'lego-42231-fast-furious-charger',
    storeId: 'amazon',
    price: 159.99,
    currency: 'USD',
    url: 'https://www.amazon.com/s?k=lego+technic+42231',
    inStock: true,
    shippingDays: { min: 1, max: 3 },
    freeShippingThreshold: FREE_SHIP.amazon,
    unitPrice: { value: 0.11, unit: 'piece' },
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- Beyblade X Xtreme Battle Set (RRP $54.99) ---
  {
    productId: 'beyblade-x-xtreme-battle-set',
    storeId: 'amazon',
    price: 49.99,
    currency: 'USD',
    url: 'https://www.amazon.com/dp/B0CS8CM4YB',
    inStock: true,
    shippingDays: { min: 1, max: 2 },
    freeShippingThreshold: FREE_SHIP.amazon,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'beyblade-x-xtreme-battle-set',
    storeId: 'target',
    price: 54.99,
    currency: 'USD',
    url: 'https://www.target.com/s?searchTerm=beyblade+x+xtreme+battle+set',
    inStock: true,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.target,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'beyblade-x-xtreme-battle-set',
    storeId: 'walmart',
    price: 52.0,
    currency: 'USD',
    url: 'https://www.walmart.com/search?q=beyblade+x+xtreme+battle+set',
    inStock: true,
    shippingDays: { min: 2, max: 5 },
    freeShippingThreshold: FREE_SHIP.walmart,
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- Beyblade X Rage Ragna Infinity Starter Pack (RRP $14.99) ---
  {
    productId: 'beyblade-x-rage-ragna-starter',
    storeId: 'amazon',
    price: 14.99,
    currency: 'USD',
    url: 'https://www.amazon.com/s?k=beyblade+x+rage+ragna',
    inStock: true,
    shippingDays: { min: 1, max: 3 },
    freeShippingThreshold: FREE_SHIP.amazon,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'beyblade-x-rage-ragna-starter',
    storeId: 'target',
    price: 14.99,
    currency: 'USD',
    url: 'https://www.target.com/s?searchTerm=beyblade+x+rage+ragna',
    inStock: false,
    shippingDays: { min: 2, max: 4 },
    freeShippingThreshold: FREE_SHIP.target,
    capturedAt: CAPTURED,
    source: 'manual',
  },

  // --- Beyblade X Clip & Rip Launcher Set (RRP $29.99) ---
  {
    productId: 'beyblade-x-clip-rip-launcher',
    storeId: 'amazon',
    price: 29.99,
    currency: 'USD',
    url: 'https://www.amazon.com/s?k=beyblade+x+clip+rip+launcher',
    inStock: true,
    shippingDays: { min: 1, max: 3 },
    freeShippingThreshold: FREE_SHIP.amazon,
    capturedAt: CAPTURED,
    source: 'manual',
  },
  {
    productId: 'beyblade-x-clip-rip-launcher',
    storeId: 'walmart',
    price: 27.94,
    currency: 'USD',
    url: 'https://www.walmart.com/search?q=beyblade+x+clip+rip+launcher',
    inStock: true,
    shippingDays: { min: 2, max: 5 },
    freeShippingThreshold: FREE_SHIP.walmart,
    capturedAt: CAPTURED,
    source: 'manual',
  },
];

