import type { Product } from './types';

// V1 seed catalog. Product details (names, set numbers, piece counts, age
// ranges, manufacturer RRP) are real, sourced from official LEGO / Mattel /
// Hasbro / Nintendo listings as of May 2026. Per-retailer price variation in
// offers.ts is modeled around RRP — see offers.ts header and PRD-04.
export const PRODUCTS: Product[] = [
  // --- LEGO Minecraft ---
  {
    id: 'lego-21274-warden-encounter',
    name: 'LEGO Minecraft The Warden Encounter 21274',
    category: 'minecraft',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/21274.png',
    ageRange: { min: 7 },
    pieceCount: 238,
    releaseYear: 2025,
    identifiers: { legoSetNumber: '21274', asin: 'B0DRW63X1Z' },
  },
  {
    id: 'lego-21265-crafting-table',
    name: 'LEGO Minecraft The Crafting Table 21265',
    category: 'minecraft',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/21265.png',
    ageRange: { min: 18 },
    pieceCount: 1195,
    releaseYear: 2024,
    identifiers: { legoSetNumber: '21265', asin: 'B0CRX64YFN' },
  },
  {
    id: 'lego-21592-chicken-rider',
    name: 'LEGO Minecraft Chicken Rider Desert Attack 21592',
    category: 'minecraft',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/21592.png',
    ageRange: { min: 6 },
    pieceCount: 79,
    releaseYear: 2026,
    identifiers: { legoSetNumber: '21592' },
  },
  {
    id: 'lego-21593-surviving-first-night',
    name: 'LEGO Minecraft Surviving The First Night 21593',
    category: 'minecraft',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/21593.png',
    ageRange: { min: 8 },
    pieceCount: 192,
    releaseYear: 2026,
    identifiers: { legoSetNumber: '21593' },
  },
  {
    id: 'lego-21595-ender-dragon',
    name: 'LEGO Minecraft The Ender Dragon 21595',
    category: 'minecraft',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/21595.png',
    ageRange: { min: 9 },
    pieceCount: 797,
    releaseYear: 2026,
    identifiers: { legoSetNumber: '21595' },
  },
  {
    id: 'lego-21597-ghast-station',
    name: 'LEGO Minecraft Ghast Station 21597',
    category: 'minecraft',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/21597.png',
    ageRange: { min: 8 },
    pieceCount: 284,
    releaseYear: 2026,
    identifiers: { legoSetNumber: '21597' },
  },

  // --- Minecraft (non-Lego) ---
  {
    id: 'minecraft-creeper-plush-8in',
    name: 'Minecraft Creeper Plush 8" (Mattel)',
    category: 'minecraft',
    subcategory: 'Plush',
    brand: 'Mattel',
    imageUrl:
      'https://i5.walmartimages.com/asr/minecraft-creeper-plush.jpeg',
    ageRange: { min: 3 },
    releaseYear: 2024,
    identifiers: { asin: 'B08HR84LWQ', targetTcin: '81510710' },
  },
  {
    id: 'minecraft-enderman-plush-7in',
    name: 'Minecraft Enderman Plush 7"',
    category: 'minecraft',
    subcategory: 'Plush',
    brand: 'Mattel',
    imageUrl:
      'https://i5.walmartimages.com/asr/minecraft-enderman-plush.jpeg',
    ageRange: { min: 3 },
    releaseYear: 2023,
    identifiers: { asin: 'B00F65I83A' },
  },
  {
    id: 'minecraft-game-switch',
    name: 'Minecraft — Nintendo Switch',
    category: 'minecraft',
    subcategory: 'Game',
    brand: 'Mojang',
    imageUrl:
      'https://assets.nintendo.com/image/upload/minecraft-switch-boxart.png',
    ageRange: { min: 7 },
    releaseYear: 2018,
    identifiers: { asin: 'B07D13QGXM' },
  },
  {
    id: 'minecraft-game-xbox',
    name: 'Minecraft — Xbox (Bedrock Edition)',
    category: 'minecraft',
    subcategory: 'Game',
    brand: 'Mojang',
    imageUrl:
      'https://store-images.s-microsoft.com/image/minecraft-xbox.png',
    ageRange: { min: 7 },
    releaseYear: 2017,
    identifiers: {},
  },

  // --- LEGO (non-Minecraft) ---
  {
    id: 'lego-75408-mandalorian-grogu-speeder',
    name: 'LEGO Star Wars Din Djarin & Grogu Speeder Bike 75408',
    category: 'lego',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/75408.png',
    ageRange: { min: 6 },
    pieceCount: 58,
    releaseYear: 2026,
    identifiers: { legoSetNumber: '75408' },
  },
  {
    id: 'lego-75409-cobb-vanth-cad-bane',
    name: 'LEGO Star Wars Cobb Vanth & Cad Bane Speeder 75409',
    category: 'lego',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/75409.png',
    ageRange: { min: 8 },
    pieceCount: 207,
    releaseYear: 2026,
    identifiers: { legoSetNumber: '75409' },
  },
  {
    id: 'lego-60440-city-coast-guard',
    name: 'LEGO City Coast Guard Rescue Boat 60440',
    category: 'lego',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/60440.png',
    ageRange: { min: 5 },
    pieceCount: 173,
    releaseYear: 2026,
    identifiers: { legoSetNumber: '60440' },
  },
  {
    id: 'lego-42231-fast-furious-charger',
    name: 'LEGO Technic Fast & Furious Dodge Charger R/T 42231',
    category: 'lego',
    subcategory: 'Lego Set',
    brand: 'LEGO',
    imageUrl: 'https://www.lego.com/cdn/cs/set/assets/42231.png',
    ageRange: { min: 10 },
    pieceCount: 1516,
    releaseYear: 2026,
    identifiers: { legoSetNumber: '42231' },
  },

  // --- Beyblade X ---
  {
    id: 'beyblade-x-xtreme-battle-set',
    name: 'Beyblade X Xtreme Battle Set (Stadium + 2 Tops + 2 Launchers)',
    category: 'beyblade',
    subcategory: 'Battle Set',
    brand: 'Hasbro',
    imageUrl: 'https://m.media-amazon.com/images/I/beyblade-x-xtreme.jpg',
    ageRange: { min: 8 },
    releaseYear: 2024,
    identifiers: { asin: 'B0CS8CM4YB' },
  },
  {
    id: 'beyblade-x-rage-ragna-starter',
    name: 'Beyblade X Rage Ragna FE 4-55Y Infinity Starter Pack',
    category: 'beyblade',
    subcategory: 'Top',
    brand: 'Hasbro',
    imageUrl: 'https://m.media-amazon.com/images/I/beyblade-rage-ragna.jpg',
    ageRange: { min: 8 },
    releaseYear: 2026,
    identifiers: {},
  },
  {
    id: 'beyblade-x-clip-rip-launcher',
    name: 'Beyblade X Clip & Rip Launcher Set',
    category: 'beyblade',
    subcategory: 'Launcher',
    brand: 'Hasbro',
    imageUrl: 'https://m.media-amazon.com/images/I/beyblade-clip-rip.jpg',
    ageRange: { min: 8 },
    releaseYear: 2026,
    identifiers: {},
  },
];

export const getProduct = (id: string): Product | undefined =>
  PRODUCTS.find((p) => p.id === id);
