"""Price refresh via Crawl4AI — PRD-04 phase 2.

Fetches real retailer prices using a local stealth browser (Crawl4AI), which
gets past the bot detection that blocks cloud fetch APIs, and regenerates
lib/catalog/offers.ts. The app ships that file as static data — fast,
offline, no backend. Re-run weekly.

    ~/.crawl4ai-venv/bin/python scripts/crawl_prices.py

A page that still blocks the crawl, or yields no parseable price, falls back
to the verified RRP from the fetch plan — the script never invents a number.

The fetch plan and seed offers are the TypeScript source of truth; this
script reads them via `node scripts/dump-catalog-json.ts`.
"""

from __future__ import annotations

import asyncio
import datetime
import json
import subprocess
import sys
from pathlib import Path

from crawler import fetch_pages
from parse_price import parse_price

REPO_ROOT = Path(__file__).resolve().parent.parent
OFFERS_PATH = REPO_ROOT / "lib" / "catalog" / "offers.ts"
TODAY = datetime.date.today().isoformat()


def load_catalog() -> tuple[list[dict], list[dict]]:
    """Read the fetch plan + seed offers from the TypeScript source."""
    out = subprocess.run(
        [
            "node",
            "--experimental-strip-types",
            str(REPO_ROOT / "scripts" / "dump-catalog-json.ts"),
        ],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    if out.returncode != 0:
        raise RuntimeError(f"dump-catalog-json failed: {out.stderr}")
    data = json.loads(out.stdout)
    return data["fetchPlan"], data["seedOffers"]


def seed_lookup(seed_offers: list[dict], product_id: str, store_id: str):
    for o in seed_offers:
        if o["productId"] == product_id and o["storeId"] == store_id:
            return o
    return None


def render_offers_ts(offers: list[dict]) -> str:
    header = (
        f"// AUTO-GENERATED by scripts/crawl_prices.py on {TODAY}.\n"
        "// Do not edit by hand — re-run the script to refresh.\n"
        "// The hand-authored seed lives in offers.seed.ts.\n"
        "// Prices marked source: 'scrape' are live retailer prices fetched\n"
        "// via Crawl4AI; source: 'manual' means the crawl missed and the\n"
        "// value is the verified manufacturer RRP fallback.\n"
    )
    body = (
        "import type { Offer } from './types';\n\n"
        f"export const OFFERS: Offer[] = {json.dumps(offers, indent=2)};\n\n"
        "export const getOffersFor = (productId: string): Offer[] =>\n"
        "  OFFERS.filter((o) => o.productId === productId);\n"
    )
    return header + "\n" + body


async def main() -> None:
    fetch_plan, seed_offers = load_catalog()

    targets = [
        (plan, target)
        for plan in fetch_plan
        for target in plan["targets"]
        if target.get("productPage")
    ]
    urls = [t["url"] for _, t in targets]
    print(f"Crawling {len(urls)} product pages with Crawl4AI...")
    pages = await fetch_pages(urls)

    offers: list[dict] = []
    scraped = 0
    fallback = 0

    for plan, target in targets:
        store_id = target["storeId"]
        prior = seed_lookup(seed_offers, plan["productId"], store_id)
        page = pages.get(target["url"])
        text = page.markdown if page and page.ok else None
        price = parse_price(text, store_id, plan["rrp"])

        used_price = price if price is not None else plan["rrp"]
        if price is not None:
            scraped += 1
        else:
            fallback += 1

        offer = {
            "productId": plan["productId"],
            "storeId": store_id,
            "price": used_price,
            "currency": "USD",
            "url": target["url"],
            "inStock": (prior or {}).get("inStock", True),
            "capturedAt": TODAY,
            "source": "scrape" if price is not None else "manual",
        }
        # Carry stable, non-scraped facts over from the seed.
        for key in ("shippingDays", "freeShippingThreshold",
                    "membershipPrice", "unitPrice"):
            if prior and prior.get(key) is not None:
                offer[key] = prior[key]

        offers.append(offer)
        tag = "scraped" if price is not None else "RRP fallback"
        print(
            f"  {plan['productId']} @ {store_id}: "
            f"${used_price:.2f} ({tag})"
        )

    OFFERS_PATH.write_text(render_offers_ts(offers))
    print(
        f"\nWrote {len(offers)} offers to {OFFERS_PATH.relative_to(REPO_ROOT)} "
        f"({scraped} scraped, {fallback} RRP fallback)."
    )


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception as exc:  # noqa: BLE001
        print(f"crawl_prices failed: {exc}", file=sys.stderr)
        sys.exit(1)
