"""Price refresh via Crawl4AI — PRD-04 phase 2.

Single source of truth: lib/catalog/products.ts. For each product, this
derives retailer URLs from its `identifiers` (asin -> Amazon, targetTcin ->
Target, walmartItemId -> Walmart), crawls them with a local stealth browser,
parses prices, and regenerates lib/catalog/offers.ts.

    ~/.crawl4ai-venv/bin/python scripts/crawl_prices.py

No separate fetch plan or seed file — regenerating products.ts and re-running
this keeps offers.ts in sync automatically. A page that blocks the crawl or
yields no parseable price is simply omitted (no fabricated fallback); every
offer in the output is a real scraped price.

Shipping windows / free-shipping thresholds are retailer-stable defaults
defined below, not scraped.
"""

from __future__ import annotations

import asyncio
import datetime
import json
import subprocess
import sys
from pathlib import Path

from crawler import fetch_pages
from parse_price import parse_price

REPO_ROOT = Path(__file__).resolve().parent.parent
OFFERS_PATH = REPO_ROOT / "lib" / "catalog" / "offers.ts"
TODAY = datetime.date.today().isoformat()

# Retailer-stable facts — not scraped. (storeId -> shipping defaults)
STORE_DEFAULTS = {
    "amazon": {"shippingDays": (1, 2), "freeShippingThreshold": 35},
    "target": {"shippingDays": (2, 4), "freeShippingThreshold": 35},
    "walmart": {"shippingDays": (2, 4), "freeShippingThreshold": 35},
    "lego": {"shippingDays": (3, 5), "freeShippingThreshold": 35},
    "bestbuy": {"shippingDays": (2, 5), "freeShippingThreshold": 35},
    "gamestop": {"shippingDays": (3, 6), "freeShippingThreshold": 59},
}


def retail_targets(product: dict) -> list[tuple[str, str]]:
    """Build (storeId, url) pairs for a product.

    The Amazon offer is derived from identifiers.asin (the /dp/ form is
    stable). Other retailers come from product.retailerUrls — full verified
    URLs, since Target/Walmart URLs need a slug that can't be rebuilt from
    an ID alone.
    """
    targets: list[tuple[str, str]] = []
    asin = product.get("identifiers", {}).get("asin")
    if asin:
        targets.append(("amazon", f"https://www.amazon.com/dp/{asin}"))
    for store_id, url in (product.get("retailerUrls") or {}).items():
        targets.append((store_id, url))
    return targets


def load_products() -> list[dict]:
    out = subprocess.run(
        ["node", "--experimental-strip-types",
         str(REPO_ROOT / "scripts" / "dump-catalog-json.ts")],
        capture_output=True, text=True, cwd=REPO_ROOT,
    )
    if out.returncode != 0:
        raise RuntimeError(f"dump-catalog-json failed: {out.stderr}")
    return json.loads(out.stdout)["products"]


def reference_price(product: dict) -> float | None:
    """The product's known RRP for scrape noise-rejection, or None when the
    catalog has none (the parser then uses a wide absolute band)."""
    rrp = product.get("rrp")
    return float(rrp) if rrp is not None else None


def render_offers_ts(offers: list[dict]) -> str:
    header = (
        f"// AUTO-GENERATED by scripts/crawl_prices.py on {TODAY}.\n"
        "// Do not edit by hand — re-run the script to refresh.\n"
        "// Offer URLs and prices derive from products.ts identifiers;\n"
        "// every price here was scraped live via Crawl4AI.\n"
    )
    body = (
        "import type { Offer } from './types';\n\n"
        f"export const OFFERS: Offer[] = {json.dumps(offers, indent=2)};\n\n"
        "export const getOffersFor = (productId: string): Offer[] =>\n"
        "  OFFERS.filter((o) => o.productId === productId);\n"
    )
    return header + "\n" + body


async def main() -> None:
    products = load_products()
    targets = [
        (p, store_id, url)
        for p in products
        for store_id, url in retail_targets(p)
    ]
    urls = [t[2] for t in targets]
    print(f"Crawling {len(urls)} retailer pages for {len(products)} products...")
    pages = await fetch_pages(urls)

    offers: list[dict] = []
    missed = 0

    for product, store_id, url in targets:
        page = pages.get(url)
        text = page.markdown if page and page.ok else None
        price = parse_price(text, store_id, reference_price(product))
        if price is None:
            missed += 1
            print(f"  {product['id']} @ {store_id}: -- (no price, omitted)")
            continue

        defaults = STORE_DEFAULTS.get(store_id, {})
        ship = defaults.get("shippingDays")
        offer = {
            "productId": product["id"],
            "storeId": store_id,
            "price": price,
            "currency": "USD",
            "url": url,
            "inStock": True,
            "capturedAt": TODAY,
            "source": "scrape",
        }
        if ship:
            offer["shippingDays"] = {"min": ship[0], "max": ship[1]}
        if defaults.get("freeShippingThreshold"):
            offer["freeShippingThreshold"] = defaults["freeShippingThreshold"]
        offers.append(offer)
        print(f"  {product['id']} @ {store_id}: ${price:.2f} (scraped)")

    OFFERS_PATH.write_text(render_offers_ts(offers))
    print(
        f"\nWrote {len(offers)} offers to "
        f"{OFFERS_PATH.relative_to(REPO_ROOT)} ({missed} pages had no price)."
    )


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception as exc:  # noqa: BLE001
        print(f"crawl_prices failed: {exc}", file=sys.stderr)
        sys.exit(1)
