"""Catalog generator — discovers products from retailer category pages and
writes lib/catalog/products.ts.

Pipeline: crawl source search pages -> discover (name, asin, url) candidates
-> filter to kid-appropriate on-category items -> build typed Product records
-> write products.ts. Then run crawl_prices.py to populate offers.ts.

    ~/.crawl4ai-venv/bin/python scripts/generate_catalog.py

Sources are curated in SOURCES below — human-picked SEARCHES, not products.
Discovery is automated but noisy by nature; low-confidence items are written
with a `// REVIEW:` comment so a human can do a final pass. The script never
invents a product — every entry traces to a real Amazon listing it found.
"""

from __future__ import annotations

import asyncio
import datetime
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from crawler import fetch_pages
from discover import discover_from_markdown
from filter_products import FilteredCandidate, filter_candidates

REPO_ROOT = Path(__file__).resolve().parent.parent
TODAY = datetime.date.today().isoformat()

# --preview writes to products.generated.ts for inspection instead of
# overwriting the live, verified products.ts. crawl_prices.py derives offers
# straight from products.ts, so a regenerated catalog stays consistent — but
# preview first so autodiscovered junk doesn't reach the live catalog blind.
PREVIEW = "--preview" in sys.argv
PRODUCTS_PATH = REPO_ROOT / "lib" / "catalog" / (
    "products.generated.ts" if PREVIEW else "products.ts"
)

# How many discovered items to keep per source, after filtering.
PER_SOURCE_LIMIT = 12


@dataclass
class Source:
    category: str  # ProductCategory: 'minecraft' | 'lego' | 'beyblade'
    search_url: str
    require_terms: tuple[str, ...]


# Curated discovery sources. Add/adjust these to grow the catalog — the
# products themselves are discovered, not listed.
SOURCES = [
    Source(
        "minecraft",
        "https://www.amazon.com/s?k=minecraft+toys&i=toys-and-games",
        ("minecraft",),
    ),
    Source(
        "minecraft",
        "https://www.amazon.com/s?k=minecraft+plush&i=toys-and-games",
        ("minecraft",),
    ),
    Source(
        "lego",
        "https://www.amazon.com/s?k=lego+minecraft&i=toys-and-games",
        ("lego",),
    ),
    Source(
        "lego",
        "https://www.amazon.com/s?k=lego+set+kids&i=toys-and-games",
        ("lego",),
    ),
    Source(
        "beyblade",
        "https://www.amazon.com/s?k=beyblade+x&i=toys-and-games",
        ("beyblade",),
    ),
]


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:60]


def guess_brand(name: str) -> str | None:
    name_lc = name.lower()
    for brand in ("LEGO", "Mattel", "Hasbro", "Nerf", "Funko"):
        if brand.lower() in name_lc:
            return brand
    return None


def guess_subcategory(name: str, category: str) -> str:
    name_lc = name.lower()
    if category == "lego" or "lego" in name_lc:
        return "Lego Set"
    if "plush" in name_lc:
        return "Plush"
    if "launcher" in name_lc:
        return "Launcher"
    if "battle set" in name_lc or "stadium" in name_lc:
        return "Battle Set"
    if "figure" in name_lc or "action figure" in name_lc:
        return "Figure"
    return "Figure"


_LEGO_SET_RE = re.compile(r"\b(\d{4,6})\b")


def lego_set_number(name: str) -> str | None:
    # LEGO set numbers are 4-6 digit, usually at the end of the name.
    matches = _LEGO_SET_RE.findall(name)
    return matches[-1] if matches else None


def build_product(fc: FilteredCandidate) -> dict:
    c = fc.candidate
    name = c.name
    set_no = lego_set_number(name) if fc.category in ("lego", "minecraft") else None
    pid_base = slugify(name)
    identifiers: dict[str, str] = {"asin": c.asin}
    if set_no:
        identifiers["legoSetNumber"] = set_no

    product: dict = {
        "id": pid_base,
        "name": name,
        "category": fc.category,
        "subcategory": guess_subcategory(name, fc.category),
        "imageUrl": f"https://m.media-amazon.com/images/I/{c.asin}.jpg",
        "identifiers": identifiers,
        "_confidence": fc.confidence,
        "_note": fc.note,
    }
    brand = guess_brand(name)
    if brand:
        product["brand"] = brand
    return product


def render_products_ts(products: list[dict]) -> str:
    header = (
        f"// AUTO-GENERATED by scripts/generate_catalog.py on {TODAY}.\n"
        "// Products discovered from retailer category pages, then filtered.\n"
        "// Lines marked REVIEW are low-confidence — verify before relying on them.\n"
        "// Re-run the generator to refresh; do not hand-edit.\n"
    )
    entries = []
    for p in products:
        confidence = p.pop("_confidence", "high")
        note = p.pop("_note", "")
        body = json.dumps(p, indent=2)
        prefix = ""
        if confidence == "low":
            prefix = f"  // REVIEW: {note or 'low confidence'}\n"
        entries.append(prefix + "  " + body.replace("\n", "\n  "))

    return (
        header
        + "\nimport type { Product } from './types';\n\n"
        + "export const PRODUCTS: Product[] = [\n"
        + ",\n".join(entries)
        + ",\n];\n\n"
        + "export const getProduct = (id: string): Product | undefined =>\n"
        + "  PRODUCTS.find((p) => p.id === id);\n"
    )


async def main() -> None:
    print(f"Discovering products from {len(SOURCES)} sources...")
    pages = await fetch_pages([s.search_url for s in SOURCES])

    all_products: list[dict] = []
    seen_ids: set[str] = set()

    for source in SOURCES:
        page = pages.get(source.search_url)
        if not page or not page.ok:
            print(f"  ! {source.search_url}: fetch failed")
            continue
        candidates = discover_from_markdown(page.markdown)
        kept, rejected = filter_candidates(
            candidates,
            category=source.category,
            require_terms=source.require_terms,
        )
        print(
            f"  {source.search_url.split('k=')[1].split('&')[0]}: "
            f"{len(candidates)} found, {len(kept)} kept, "
            f"{len(rejected)} rejected"
        )
        for fc in kept[:PER_SOURCE_LIMIT]:
            product = build_product(fc)
            if product["id"] in seen_ids:
                continue
            seen_ids.add(product["id"])
            all_products.append(product)

    if not all_products:
        raise RuntimeError("no products discovered — aborting, keeping old catalog")

    lows = sum(1 for p in all_products if p.get("_confidence") == "low")
    PRODUCTS_PATH.write_text(render_products_ts(all_products))
    print(
        f"\nWrote {len(all_products)} products to "
        f"{PRODUCTS_PATH.relative_to(REPO_ROOT)} "
        f"({lows} flagged for review)."
    )
    print("Next: run crawl_prices.py to populate offers.ts.")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception as exc:  # noqa: BLE001
        print(f"generate_catalog failed: {exc}", file=sys.stderr)
        sys.exit(1)
