// Price refresh script — PRD-04 phase 2.
//
// Fetches real retailer prices via the TinyFish Fetch API and writes
// lib/catalog/offers.generated.ts. The app ships that generated file as
// static data: fast, offline, no backend. Re-run this weekly to refresh.
//
//   TINYFISH_API_KEY=... node --experimental-strip-types scripts/refresh-prices.ts
//
// A retailer page that blocks the fetch or yields no parseable price falls
// back to the verified RRP from fetchPlan.ts — the script never invents a
// number. Each offer records whether its price was scraped or is an RRP
// fallback, and the date it was captured.

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { SEED_OFFERS } from '../lib/catalog/offers.seed.ts';
import type { Offer } from '../lib/catalog/types.ts';
import { FETCH_PLAN } from './fetchPlan.ts';
import { parsePrice } from './parsePrice.ts';
import { fetchAll, type FetchResult } from './tinyfish.ts';

const TODAY = new Date().toISOString().slice(0, 10);

// Stable per-(product,store) facts that are not scraped: shipping window,
// free-shipping threshold, in-stock, unit price. Carried over from the seed
// offers so a refresh only touches price/date/source.
function priorOffer(productId: string, storeId: string): Offer | undefined {
  return SEED_OFFERS.find(
    (o) => o.productId === productId && o.storeId === storeId
  );
}

async function main(): Promise<void> {
  // --offline skips the network entirely: every offer becomes the verified
  // RRP fallback. Use it to correct the catalog without a TinyFish key.
  const offline = process.argv.includes('--offline');

  const allUrls = FETCH_PLAN.flatMap((p) => p.targets.map((t) => t.url));
  let fetched = new Map<string, FetchResult>();
  if (offline) {
    console.log('Offline mode — using verified RRP for every offer.');
  } else {
    console.log(`Fetching ${allUrls.length} retailer pages via TinyFish...`);
    fetched = await fetchAll(allUrls);
  }

  const offers: Offer[] = [];
  let scraped = 0;
  let fallback = 0;

  for (const plan of FETCH_PLAN) {
    for (const target of plan.targets) {
      const prior = priorOffer(plan.productId, target.storeId);
      const page = fetched.get(target.url);
      const price = parsePrice(page?.text ?? null, { rrp: plan.rrp });

      const usedPrice = price ?? plan.rrp;
      if (price !== null) scraped++;
      else fallback++;

      offers.push({
        productId: plan.productId,
        storeId: target.storeId,
        price: usedPrice,
        currency: 'USD',
        url: target.url,
        inStock: prior?.inStock ?? true,
        shippingDays: prior?.shippingDays,
        freeShippingThreshold: prior?.freeShippingThreshold,
        membershipPrice: prior?.membershipPrice,
        unitPrice: prior?.unitPrice,
        capturedAt: TODAY,
        source: price !== null ? 'scrape' : 'manual',
      });

      const tag = price !== null ? 'scraped' : 'RRP fallback';
      console.log(
        `  ${plan.productId} @ ${target.storeId}: $${usedPrice.toFixed(
          2
        )} (${tag})`
      );
    }
  }

  const header = `// AUTO-GENERATED by scripts/refresh-prices.ts on ${TODAY}.
// Do not edit by hand — re-run the script to refresh.
// The hand-authored seed lives in offers.seed.ts.
// Prices marked source: 'scrape' are live retailer prices fetched via
// TinyFish; source: 'manual' means the fetch missed and the value is the
// verified manufacturer RRP fallback.
`;
  const body = `import type { Offer } from './types';

export const OFFERS: Offer[] = ${JSON.stringify(offers, null, 2)};

export const getOffersFor = (productId: string): Offer[] =>
  OFFERS.filter((o) => o.productId === productId);
`;

  const outPath = join('lib', 'catalog', 'offers.ts');
  writeFileSync(outPath, header + '\n' + body);

  console.log(
    `\nWrote ${offers.length} offers to ${outPath} ` +
      `(${scraped} scraped, ${fallback} RRP fallback).`
  );
}

main().catch((err) => {
  console.error('refresh-prices failed:', err.message);
  process.exit(1);
});
